In [45]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
data_preprocessed=pd.read_csv("/content/preprocessed.csv")

In [3]:
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4        Date  \
0           0         0         0         1  2015-07-07   
1           0         0         0         0  2015-07-14   
2           0         0         0         1  2015-07-15   
3           1         0         0         0  2015-07-16   
4           0         0         0         1  2015-07-23   
..        ...       ...       ...       ...         ...   
695         1         0         0         0  2018-05-23   
696         1         0         0         0  2018-05-23   
697         1         0         0         0  2018-05-24   
698         0         0         0         1  2018-05-24   
699         0         0         0         1  2018-05-31   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0                 30          0         2     1                          4   
1                 31          0         1     0                          0   
2                 31          0         0     0                          2   
3                 24          0         2     0                          4   
4                 30          0         2     1                          2   
..               ...        ...       ...   ...                        ...   
695               22          1         2     0                          8   
696               24          0         1     2                          3   
697               25          1         0     0                          8   
698               25          1         0     0                          2   
699               25          0         1     1                          2   

     month  weekday  
0        7        1  
1        7        1  
2        7        2  
3        7        3  
4        7        3  
..     ...      ...  
695      5        2  
696      5        2  
697      5        3  
698      5        3  
699      5        3  

[700 rows x 16 columns]

In [4]:
data_preprocessed["Absenteeism Time in Hours"].median()

3.0

In [5]:
target=np.where(data_preprocessed["Absenteeism Time in Hours"]>data_preprocessed["Absenteeism Time in Hours"].median(),1,0)

In [6]:
target

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed["excess_absenteeism"]=target

In [8]:
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4        Date  \
0           0         0         0         1  2015-07-07   
1           0         0         0         0  2015-07-14   
2           0         0         0         1  2015-07-15   
3           1         0         0         0  2015-07-16   
4           0         0         0         1  2015-07-23   
..        ...       ...       ...       ...         ...   
695         1         0         0         0  2018-05-23   
696         1         0         0         0  2018-05-23   
697         1         0         0         0  2018-05-24   
698         0         0         0         1  2018-05-24   
699         0         0         0         1  2018-05-31   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0                 30          0         2     1                          4   
1                 31          0         1     0                          0   
2                 31          0         0     0                          2   
3                 24          0         2     0                          4   
4                 30          0         2     1                          2   
..               ...        ...       ...   ...                        ...   
695               22          1         2     0                          8   
696               24          0         1     2                          3   
697               25          1         0     0                          8   
698               25          1         0     0                          2   
699               25          0         1     1                          2   

     month  weekday  excess_absenteeism  
0        7        1                   1  
1        7        1                   0  
2        7        2                   0  
3        7        3                   1  
4        7        3                   0  
..     ...      ...                 ...  
695      5        2                   1  
696      5        2                   0  
697      5        3                   1  
698      5        3                   0  
699      5        3                   0  

[700 rows x 17 columns]

In [9]:
target.sum()/len(target)

0.45571428571428574

In [10]:
target.shape[0]

700

In [11]:
target.sum()

319

In [12]:
data_with_target=data_preprocessed.drop(["Absenteeism Time in Hours"],axis=1)

In [13]:
data_with_target=data_with_target.drop(["Date"],axis=1)

In [14]:
data_checkpoint_1=data_with_target.copy()

In [15]:
unscaled_inputs=data_with_target.iloc[:,:-1]

In [16]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler=StandardScaler()

In [17]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [18]:
scaled_input=absenteeism_scaler.transform(unscaled_inputs)

In [19]:
scaled_input.shape

(700, 14)

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
train_test_split(scaled_input,target,train_size=0.8,random_state=20)

[array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
          1.61027597,  0.66825259],
        [-0.57735027, -0.09298136,  3.17979734, ..., -0.58968976,
          1.32476605, -0.00772546],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.58968976,
          1.03925612,  1.34423065],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
          0.7537462 ,  1.34423065],
        [-0.57735027, -0.09298136, -0.31448545, ...,  2.8430157 ,
          0.18272635,  1.34423065],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
          1.61027597, -1.35968157]]),
 array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
          1.32476605,  1.34423065],
        [-0.57735027, -0.09298136, -0.31448545, ...,  0.26848661,
          0.7537462 ,  1.34423065],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
          1.32476605, -1.35968157],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ...,  

In [22]:
x_train,x_test,y_train,y_test=train_test_split(scaled_input,target,train_size=0.8,random_state=20)

In [23]:
x_train.shape

(560, 14)

In [24]:
x_test.shape

(140, 14)

In [25]:
from sklearn.linear_model import LogisticRegression

In [26]:
from sklearn import metrics

In [27]:
reg=LogisticRegression()

In [28]:
reg.fit(x_train,y_train)

LogisticRegression()

In [29]:
reg.score(x_train,y_train)

0.7839285714285714

In [30]:
model_output=reg.predict(x_train)

In [31]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [32]:
np.sum(model_output==y_train)

439

In [33]:
y_train.shape[0]

560

In [34]:
accuracy=np.sum(model_output==y_train)/y_train.shape[0]

In [35]:
accuracy

0.7839285714285714

In [36]:
reg.intercept_


array([-0.22206736])

In [37]:
reg.coef_

array([[ 2.07601767,  0.33504757,  1.56162303,  1.32927434,  0.70639316,
        -0.03986811, -0.20089491, -0.00456366,  0.31933564, -0.135508  ,
         0.38172443, -0.3332426 ,  0.18793677, -0.07062253]])

In [38]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'month', 'weekday'], dtype=object)

In [39]:
summary_data=pd.DataFrame(columns=["features"],data=unscaled_inputs.columns.values)
summary_data["coefficient"]=np.transpose(reg.coef_)


In [40]:
summary_data

features  coefficient
0                  Reason_1     2.076018
1                  Reason_2     0.335048
2                  Reason_3     1.561623
3                  Reason_4     1.329274
4    Transportation Expense     0.706393
5          Distance to Work    -0.039868
6                       Age    -0.200895
7   Daily Work Load Average    -0.004564
8           Body Mass Index     0.319336
9                 Education    -0.135508
10                 Children     0.381724
11                     Pets    -0.333243
12                    month     0.187937
13                  weekday    -0.070623

In [41]:
summary_data.index=summary_data.index+1


In [42]:
summary_data

features  coefficient
1                  Reason_1     2.076018
2                  Reason_2     0.335048
3                  Reason_3     1.561623
4                  Reason_4     1.329274
5    Transportation Expense     0.706393
6          Distance to Work    -0.039868
7                       Age    -0.200895
8   Daily Work Load Average    -0.004564
9           Body Mass Index     0.319336
10                Education    -0.135508
11                 Children     0.381724
12                     Pets    -0.333243
13                    month     0.187937
14                  weekday    -0.070623

In [43]:
summary_data.loc[0]=["intercept",reg.intercept_[0]]


In [44]:
summary_data.sort_index()

features  coefficient
0                 intercept    -0.222067
1                  Reason_1     2.076018
2                  Reason_2     0.335048
3                  Reason_3     1.561623
4                  Reason_4     1.329274
5    Transportation Expense     0.706393
6          Distance to Work    -0.039868
7                       Age    -0.200895
8   Daily Work Load Average    -0.004564
9           Body Mass Index     0.319336
10                Education    -0.135508
11                 Children     0.381724
12                     Pets    -0.333243
13                    month     0.187937
14                  weekday    -0.070623